project:
  type: website

website:
  title: "Asutosh Ghanto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: sketchy
    css: styles.css



