project:
  type: website
  output-dir: docs

website:
  title: "Asutosh Ghanto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    number-sections: true
    code-fold: true
    code-line-numbers: true



